spring:
  datasource:
    # url: jdbc:mysql://13.124.245.202:3306/musicat_audio?characterEncoding=UTF-8&serverTimezone=UTC
    url: jdbc:mysql://184.72.42.251:3306/mini
    # url: jdbc:mysql://127.0.0.1:3306/mini
    username: root
    password: mymysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: validate
      #ddl-auto: create
    properties:
      hibernate:
        show_sql: true #sysout으로 찍는다
        format_sql: true

  # using generated security password 뜨지 않도록 비밀번호 부여
  security:
    user:
      password: 1111