spring:
  datasource:
    # url: jdbc:mysql://13.124.245.202:3306/musicat_audio?characterEncoding=UTF-8&serverTimezone=UTC
    url: jdbc:mysql://184.72.42.251:3306/mini
    # url: jdbc:mysql://127.0.0.1:3306/mini
    username: root
    password: mymysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: validate
      #ddl-auto: create
    properties:
      hibernate:
        show_sql: true #sysout으로 찍는다
        format_sql: true

  # using generated security password 뜨지 않도록 비밀번호 부여
  security:
    user:
      password: 1111

  jwt:
    header: Authorization
    # secret: bWluaS1wcm9qZWN0LXRlYW15LXllYW5hLWRheWVh
    access-token-validity-in-seconds: 60
    refresh-token-validity-in-seconds: 60

  redis:
    host: 184.72.42.251 # 127.0.0.1
    password: myredis
    port: 6379
    lettuce: #jedis : 별도 의존성 필요 / lettuce : 별도 설정 필요 없음, 비동기로 요청을 처리(Netty)
      pool:
        max-active: 8 #pool에 할당할 수 있는 커넥션 최대수
        max-idle: 10 #pool의 "idle" 커넥션 최대 수
        min-idle: 2 #pool에서 관리하는 idle 커넥션의 최소 수